name: Matrix
on: [push]

jobs:
  node-matrix:
    continue-on-error: false
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [14, 15, 16, 17]
        experimental: [false]  # Default value for experimental is false
        include:
          # Adding specific combinations for ubuntu and macos
          - os: ubuntu-latest
            node-version: 16
            experimental: true
          - os: macos-latest
            node-version: 15
        exclude:
          # Exclude specific combinations
          - os: ubuntu-latest
            node-version: 14
      fail-fast: false
      # max-parallel: 3
    runs-on: ${{ matrix.os }}
    steps:
      - run: node -v
      - run: echo '${{ toJson(matrix) }}'
