name: Status Check Functions
on: [push]

jobs:
    job-1:
        runs-on: ubuntu-latest
        timeout-minutes: 1
        steps:
            - name: step 1
              run: sleep 90
             # timeout-minutes: 1
            - name: step 2
              id: step-2
              continue-on-error: true
              run: exit 1
            - name: Runs on step 2 Failure
              if: failure() && steps.step-2.conclusion == 'failure'
              run: echo 'step 2 has failed'
            - name: Runs on Failure
              if: failure()
              run: echo 'Filure'  
            - name: Runs on success
            ### This is not needed (Default Behaviour)
              if: success()
              run: echo 'Runs on Success'
            - name: Always Runs
            # if: success() || failure()
              if: always()  
              run: echo 'Always Runs'
            - name: Runs when Cancelled
              if: cancelled()
              run: echo 'Runs on Canceled'  

    job-2:
      runs-on: ubuntu-latest
      needs: job-1
      if: failure()
      steps:
        - run: echo 'Job 2'