name: Variables and Secrets
on: [push]

jobs:
    log-vars:
        runs-on: ${{ vars.JOBS_RUNNER }}
        environment: "production"

        env:
            BOOLEAN_SECRET: ${{ secrets.BOOLEAN_SECRET }}
            ENV_LEVEL_VAR: ${{ Vars.ENV_LEVEL_VAR }}
            REPO_LEVEL_VAR: ${{ vars.REPO_LEVEL_VAR }}
            ORG_LEVEL_VAR: ${{ vars.ORG_LEVEL_VAR }}
        steps:
           - name: Run only if BOOLEAN_SECRET is false   
             if: env.BOOLEAN_SECRET == 'false'
             run: echo 'I ran BOOLEAN_SECRET which was set to true'
           - name: LOG Vars
             run: |
               echo '${{ vars.JOBS_RUNNER }}'
               echo "ORG_LEVEL_VAR: $ORG_LEVEL_VAR"
               echo "REPO_LEVEL_VAR: $REPO_LEVEL_VAR"
               echo "ENV_LEVEL_VAR: $ENV_LEVEL_VAR"
